default:
  image: node:lts-alpine

stages:
  - deploy

deploy-job:
  stage: deploy
  only:
    - main
  before_script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >.npmrc
  script:
    - echo "NPM clean install..."
    - npm ci
    - npm run build --if-present
    - echo "⚠️ Should run tests locally to verify Mango URI parsing..."
    - npm publish
